-- Notenfuchs initial schema

CREATE TABLE grade_scale (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL UNIQUE,
    min             NUMERIC(4,2) NOT NULL,
    max             NUMERIC(4,2) NOT NULL,
    lower_is_better BOOLEAN NOT NULL
);

CREATE TABLE school_class (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    school_year VARCHAR(255) NOT NULL
);

CREATE TABLE student (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_class_id BIGINT NOT NULL REFERENCES school_class(id) ON DELETE CASCADE,
    name           VARCHAR(255) NOT NULL,
    display_name   VARCHAR(255)
);

CREATE TABLE subject (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_class_id BIGINT NOT NULL REFERENCES school_class(id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    grade_scale_id  BIGINT NOT NULL REFERENCES grade_scale(id),
    rounding_mode   VARCHAR(32) NOT NULL DEFAULT 'COMMERCIAL'
);

CREATE TABLE grade_category (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id     BIGINT NOT NULL REFERENCES subject(id) ON DELETE CASCADE,
    name           VARCHAR(255) NOT NULL,
    weight_percent NUMERIC(5,2) NOT NULL
);

CREATE TABLE assessment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES grade_category(id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    date        DATE,
    factor      NUMERIC(5,2) NOT NULL DEFAULT 1.00
);

CREATE TABLE grade (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
    student_id    BIGINT NOT NULL REFERENCES student(id) ON DELETE CASCADE,
    value         NUMERIC(4,2) NOT NULL
);

CREATE INDEX idx_student_school_class ON student(school_class_id);
CREATE INDEX idx_subject_school_class ON subject(school_class_id);
CREATE INDEX idx_subject_grade_scale ON subject(grade_scale_id);
CREATE INDEX idx_grade_category_subject ON grade_category(subject_id);
CREATE INDEX idx_assessment_category ON assessment(category_id);
CREATE INDEX idx_grade_assessment ON grade(assessment_id);
CREATE INDEX idx_grade_student ON grade(student_id);

-- Seed: the German 1-6 grading scale (1 = best, 6 = worst). Supports tendencies
-- (e.g. 1.3, 1.7, 2.3) as plain decimals. Additional scales (e.g. a future 0-15
-- "Punkte" scale) can be added later with a simple INSERT - no schema change needed,
-- because grade values are stored as NUMERIC, not as an enum tied to this scale.
INSERT INTO grade_scale (name, min, max, lower_is_better)
VALUES ('DE 1-6', 1, 6, true);

-- Hibernate ORM 7 (Quarkus 3.37+) resolves GenerationType.AUTO on Panache
-- entities to a per-entity pooled sequence generator, not the native
-- IDENTITY columns this schema is built for (older Hibernate mapped AUTO to
-- IDENTITY on PostgreSQL). The identity columns stay in place - this just
-- adds the sequences Hibernate expects at startup schema validation.
--
-- Pool size (50) and start value must match exactly what Hibernate's
-- SequenceStyleGenerator creates (verified against its generated DDL),
-- or its block-allocation optimizer will hand out ids the sequence hasn't
-- actually reserved. Each sequence is seeded past any existing max id so
-- newly Hibernate-generated ids can't collide with rows already inserted
-- via the identity default (e.g. the seeded "DE 1-6" grade_scale row).

CREATE SEQUENCE grade_scale_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE school_class_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE student_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE subject_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE grade_category_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE assessment_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE grade_seq START WITH 1 INCREMENT BY 50;

SELECT setval('grade_scale_seq', COALESCE((SELECT MAX(id) FROM grade_scale), 0) + 1, false);
SELECT setval('school_class_seq', COALESCE((SELECT MAX(id) FROM school_class), 0) + 1, false);
SELECT setval('student_seq', COALESCE((SELECT MAX(id) FROM student), 0) + 1, false);
SELECT setval('subject_seq', COALESCE((SELECT MAX(id) FROM subject), 0) + 1, false);
SELECT setval('grade_category_seq', COALESCE((SELECT MAX(id) FROM grade_category), 0) + 1, false);
SELECT setval('assessment_seq', COALESCE((SELECT MAX(id) FROM assessment), 0) + 1, false);
SELECT setval('grade_seq', COALESCE((SELECT MAX(id) FROM grade), 0) + 1, false);
