-- Notenfuchs initial schema

CREATE TABLE grade_scale (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL UNIQUE,
    min             NUMERIC(4,2) NOT NULL,
    max             NUMERIC(4,2) NOT NULL,
    lower_is_better BOOLEAN NOT NULL
);

CREATE TABLE school_class (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    school_year VARCHAR(255) NOT NULL
);

CREATE TABLE student (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_class_id BIGINT NOT NULL REFERENCES school_class(id),
    name           VARCHAR(255) NOT NULL,
    display_name   VARCHAR(255)
);

CREATE TABLE subject (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_class_id BIGINT NOT NULL REFERENCES school_class(id),
    name            VARCHAR(255) NOT NULL,
    grade_scale_id  BIGINT NOT NULL REFERENCES grade_scale(id),
    rounding_mode   VARCHAR(32) NOT NULL DEFAULT 'COMMERCIAL'
);

CREATE TABLE grade_category (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id     BIGINT NOT NULL REFERENCES subject(id),
    name           VARCHAR(255) NOT NULL,
    weight_percent NUMERIC(5,2) NOT NULL
);

CREATE TABLE assessment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL REFERENCES grade_category(id),
    name        VARCHAR(255) NOT NULL,
    date        DATE,
    factor      NUMERIC(5,2) NOT NULL DEFAULT 1.00
);

CREATE TABLE grade (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES assessment(id),
    student_id    BIGINT NOT NULL REFERENCES student(id),
    value         NUMERIC(4,2) NOT NULL
);

CREATE INDEX idx_student_school_class ON student(school_class_id);
CREATE INDEX idx_subject_school_class ON subject(school_class_id);
CREATE INDEX idx_subject_grade_scale ON subject(grade_scale_id);
CREATE INDEX idx_grade_category_subject ON grade_category(subject_id);
CREATE INDEX idx_assessment_category ON assessment(category_id);
CREATE INDEX idx_grade_assessment ON grade(assessment_id);
CREATE INDEX idx_grade_student ON grade(student_id);

-- Seed: the German 1-6 grading scale (1 = best, 6 = worst). Supports tendencies
-- (e.g. 1.3, 1.7, 2.3) as plain decimals. Additional scales (e.g. a future 0-15
-- "Punkte" scale) can be added later with a simple INSERT - no schema change needed,
-- because grade values are stored as NUMERIC, not as an enum tied to this scale.
INSERT INTO grade_scale (name, min, max, lower_is_better)
VALUES ('DE 1-6', 1, 6, true);
