-- Notenfuchs initial schema

CREATE TABLE grade_scale (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL UNIQUE,
    min             NUMERIC(4,2) NOT NULL,
    max             NUMERIC(4,2) NOT NULL,
    lower_is_better BOOLEAN NOT NULL
);

CREATE TABLE school_class (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                          VARCHAR(255) NOT NULL,
    school_year                   VARCHAR(255) NOT NULL,
    owner_subject                 VARCHAR(255) NOT NULL,
    -- "Copy class into a new school year" (see ClassUiResource#duplicate) links the new class
    -- back to the one it was cloned from. Nullable and purely informational (future trend
    -- features) - never used for access control or locking, so deleting the predecessor must
    -- not be blocked by, or cascade into, a class only ever derived from it.
    predecessor_class_id          BIGINT REFERENCES school_class(id) ON DELETE SET NULL,
    -- Halbjahr (half-year) split view for the grade grid: a nullable cutoff date on the class.
    -- Purely a display/query filter - no new grade entities, no snapshots. When null, the grade
    -- grid renders exactly as before (single full-year view). When set, Assessments dated on/before
    -- the cutoff count into "1. Halbjahr", those after into "2. Halbjahr"; the whole-year average
    -- is unaffected either way.
    half_year_cutoff              DATE,
    -- How the Halbjahr split view's H1/H2 average columns are displayed: whole grades (default,
    -- unchanged behavior) or half-grades.
    half_year_grade_display       VARCHAR(10) NOT NULL DEFAULT 'WHOLE',
    -- Width, as a raw deviation from a whole grade step (e.g. 0.1 for +/-0.1), of the "plain"
    -- zone around a whole grade within which no +/- tendency suffix is shown - compared directly
    -- against a raw average rather than as a percentage that first needs converting to a fraction.
    -- NULL disables the tendency suffix entirely. Meaningful under both half_year_grade_display
    -- values (see HalfYearGradeDisplayService).
    half_year_tendency_threshold  NUMERIC(3,2)
);

CREATE TABLE student (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_class_id BIGINT NOT NULL REFERENCES school_class(id) ON DELETE CASCADE,
    name           VARCHAR(255) NOT NULL,
    display_name   VARCHAR(255)
);

CREATE TABLE subject (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_class_id BIGINT NOT NULL REFERENCES school_class(id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    grade_scale_id  BIGINT NOT NULL REFERENCES grade_scale(id),
    rounding_mode   VARCHAR(32) NOT NULL DEFAULT 'COMMERCIAL'
);

CREATE TABLE grade_category (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id     BIGINT NOT NULL REFERENCES subject(id) ON DELETE CASCADE,
    name           VARCHAR(255) NOT NULL,
    weight_percent NUMERIC(5,2) NOT NULL
);

CREATE TABLE assessment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id   BIGINT NOT NULL REFERENCES grade_category(id) ON DELETE CASCADE,
    name          VARCHAR(255) NOT NULL,
    date          DATE,
    factor        NUMERIC(5,2) NOT NULL DEFAULT 1.00,
    -- Notenschluessel (points -> grade): an Assessment can be marked "points-based" with its own
    -- configurable points-threshold-to-grade key (PointsGradeBand rows, each an absolute points
    -- anchor - no upfront "max points" needed). Grades entered against such an Assessment store
    -- the raw points (grade.points), never a frozen converted number - the grade is derived live
    -- from points + the current bands + the subject's GradeScale (see PointsConversionService),
    -- so editing either the points or the key recomputes the grade automatically.
    points_based  BOOLEAN NOT NULL DEFAULT FALSE,
    -- Per-Leistung rounding mode for a points-based Assessment's derived grade: lets a teacher
    -- choose "kaufmaennisch" (standard half-up) vs. "zugunsten des Schuelers" (round toward the
    -- better grade) independently per Assessment, mirroring subject.rounding_mode's choice for
    -- the whole-grade average rounding. Unused for a non-points-based Assessment.
    rounding_mode VARCHAR(32) NOT NULL DEFAULT 'IN_FAVOR_OF_STUDENT'
);

-- One anchor point of a points-based Assessment's Notenschluessel: `points` raw points maps
-- exactly to `grade_value`, and points falling between, below, or above two anchors
-- interpolate/extrapolate linearly (see PointsConversionService). Bands are freely configurable
-- per assessment - no Bundesland-specific scheme is imposed.
CREATE TABLE points_grade_band (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
    points        NUMERIC(6,2) NOT NULL,
    grade_value   NUMERIC(4,2) NOT NULL
);

-- grade.value is the direct-entry grade; a points-based assessment's grade rows use `points`
-- instead and leave `value` NULL (the grade is converted live, never stored) - exactly one of
-- the two is ever set, enforced by chk_grade_value_xor_points below.
CREATE TABLE grade (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
    student_id    BIGINT NOT NULL REFERENCES student(id) ON DELETE CASCADE,
    value         NUMERIC(4,2),
    points        NUMERIC(6,2),
    CONSTRAINT chk_grade_value_xor_points
        CHECK ((value IS NOT NULL AND points IS NULL) OR (value IS NULL AND points IS NOT NULL))
);

-- Verhaltensnoten: one behavior/conduct grade per (student, subject), entered directly by the
-- teacher - independent of Assessment/Grade/GradeService, never contributes to a subject's
-- academic average. No H1/H2 split: a single always-current value the teacher updates before
-- each report is printed, consistent with this app's anti-freeze design principle.
CREATE TABLE behavior_grade (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE CASCADE,
    subject_id BIGINT NOT NULL REFERENCES subject(id) ON DELETE CASCADE,
    value      NUMERIC(4,2) NOT NULL,
    UNIQUE (student_id, subject_id)
);

CREATE INDEX idx_school_class_owner_subject ON school_class(owner_subject);
CREATE INDEX idx_school_class_predecessor ON school_class(predecessor_class_id);
CREATE INDEX idx_student_school_class ON student(school_class_id);
CREATE INDEX idx_subject_school_class ON subject(school_class_id);
CREATE INDEX idx_subject_grade_scale ON subject(grade_scale_id);
CREATE INDEX idx_grade_category_subject ON grade_category(subject_id);
CREATE INDEX idx_assessment_category ON assessment(category_id);
CREATE INDEX idx_points_grade_band_assessment ON points_grade_band(assessment_id);
CREATE INDEX idx_grade_assessment ON grade(assessment_id);
CREATE INDEX idx_grade_student ON grade(student_id);
CREATE INDEX idx_behavior_grade_student ON behavior_grade(student_id);
CREATE INDEX idx_behavior_grade_subject ON behavior_grade(subject_id);

-- Seed: the German 1-6 grading scale (1 = best, 6 = worst). Supports tendencies
-- (e.g. 1.3, 1.7, 2.3) as plain decimals. Additional scales (e.g. a future 0-15
-- "Punkte" scale) can be added later with a simple INSERT - no schema change needed,
-- because grade values are stored as NUMERIC, not as an enum tied to this scale.
INSERT INTO grade_scale (name, min, max, lower_is_better)
VALUES ('DE 1-6', 1, 6, true);

-- Hibernate ORM 7 (Quarkus 3.37+) resolves GenerationType.AUTO on Panache
-- entities to a per-entity pooled sequence generator, not the native
-- IDENTITY columns this schema is built for (older Hibernate mapped AUTO to
-- IDENTITY on PostgreSQL). The identity columns stay in place - this just
-- adds the sequences Hibernate expects at startup schema validation.
--
-- Pool size (50) and start value must match exactly what Hibernate's
-- SequenceStyleGenerator creates (verified against its generated DDL),
-- or its block-allocation optimizer will hand out ids the sequence hasn't
-- actually reserved. Each sequence is seeded past any existing max id so
-- newly Hibernate-generated ids can't collide with rows already inserted
-- via the identity default (e.g. the seeded "DE 1-6" grade_scale row).

CREATE SEQUENCE grade_scale_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE school_class_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE student_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE subject_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE grade_category_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE assessment_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE points_grade_band_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE grade_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE behavior_grade_seq START WITH 1 INCREMENT BY 50;

SELECT setval('grade_scale_seq', COALESCE((SELECT MAX(id) FROM grade_scale), 0) + 1, false);
SELECT setval('school_class_seq', COALESCE((SELECT MAX(id) FROM school_class), 0) + 1, false);
SELECT setval('student_seq', COALESCE((SELECT MAX(id) FROM student), 0) + 1, false);
SELECT setval('subject_seq', COALESCE((SELECT MAX(id) FROM subject), 0) + 1, false);
SELECT setval('grade_category_seq', COALESCE((SELECT MAX(id) FROM grade_category), 0) + 1, false);
SELECT setval('assessment_seq', COALESCE((SELECT MAX(id) FROM assessment), 0) + 1, false);
SELECT setval('points_grade_band_seq', COALESCE((SELECT MAX(id) FROM points_grade_band), 0) + 1, false);
SELECT setval('grade_seq', COALESCE((SELECT MAX(id) FROM grade), 0) + 1, false);
SELECT setval('behavior_grade_seq', COALESCE((SELECT MAX(id) FROM behavior_grade), 0) + 1, false);
