-- Multi-teacher access: a class can have multiple full co-owners (Klassenlehrer-tier,
-- identical rights, no hierarchy), and a subject can have multiple teachers (Fachlehrer-tier).
-- Class-level access (roster read, subject list, Verhaltensnoten) is derived, not stored: a
-- teacher has it if they own the class, or teach at least one of its subjects - see
-- OwnershipGuard. Individual Leistung/grade access is gated purely by "do you teach this
-- specific subject", true for owners and collaborators alike.
--
-- No role column on class_teacher - it only ever holds owners now that collaborator access
-- is derived from subject_teacher, so a role enum with one possible value would be pure
-- guesswork about a future that may not happen.
CREATE TABLE class_teacher (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_class_id BIGINT NOT NULL REFERENCES school_class(id) ON DELETE CASCADE,
    teacher_subject VARCHAR(255) NOT NULL,
    UNIQUE (school_class_id, teacher_subject)
);
CREATE INDEX idx_class_teacher_school_class ON class_teacher(school_class_id);
CREATE INDEX idx_class_teacher_teacher_subject ON class_teacher(teacher_subject);

-- Who can teach/grade a given subject - any current teacher of a subject can add another
-- teacher to it directly, no class-owner approval needed (see OwnershipGuard).
CREATE TABLE subject_teacher (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id      BIGINT NOT NULL REFERENCES subject(id) ON DELETE CASCADE,
    teacher_subject VARCHAR(255) NOT NULL,
    UNIQUE (subject_id, teacher_subject)
);
CREATE INDEX idx_subject_teacher_subject ON subject_teacher(subject_id);
CREATE INDEX idx_subject_teacher_teacher_subject ON subject_teacher(teacher_subject);

-- Backfill: every existing class's sole owner becomes its OWNER row and the teacher of every
-- one of its existing subjects - matches today's actual single-teacher-per-class behavior
-- exactly, so nothing changes for classes that predate this migration.
INSERT INTO class_teacher (school_class_id, teacher_subject)
SELECT id, owner_subject FROM school_class;

INSERT INTO subject_teacher (subject_id, teacher_subject)
SELECT s.id, sc.owner_subject FROM subject s JOIN school_class sc ON sc.id = s.school_class_id;

DROP INDEX idx_school_class_owner_subject;
ALTER TABLE school_class DROP COLUMN owner_subject;

-- Same pooled-sequence pattern as V1 (Hibernate ORM 7 resolves GenerationType.AUTO on Panache
-- entities to a per-entity pooled sequence generator, not native IDENTITY) - pool size and
-- start value must match Hibernate's SequenceStyleGenerator exactly, seeded past the backfilled
-- rows' max id so newly Hibernate-generated ids can't collide with them.
CREATE SEQUENCE class_teacher_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE subject_teacher_seq START WITH 1 INCREMENT BY 50;

SELECT setval('class_teacher_seq', COALESCE((SELECT MAX(id) FROM class_teacher), 0) + 1, false);
SELECT setval('subject_teacher_seq', COALESCE((SELECT MAX(id) FROM subject_teacher), 0) + 1, false);
