-- Notenschluessel (points -> grade): an Assessment can be marked "points-based" with its own
-- configurable points-threshold-to-grade key (PointsGradeBand rows, each an absolute points
-- threshold - no upfront "max points" needed). Grades entered against such an Assessment store
-- the raw points (grade.points), never a frozen converted number - the grade is derived live
-- from points + the current bands + the subject's GradeScale (see PointsConversionService),
-- so editing either the points or the key recomputes the grade automatically, consistent
-- with this app's anti-freeze design principle (see ROADMAP.md).

ALTER TABLE assessment
    ADD COLUMN points_based BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE points_grade_band (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id BIGINT NOT NULL REFERENCES assessment(id) ON DELETE CASCADE,
    min_points    NUMERIC(6,2) NOT NULL,
    grade_value   NUMERIC(4,2) NOT NULL
);

CREATE INDEX idx_points_grade_band_assessment ON points_grade_band(assessment_id);

-- grade.value stays the direct-entry grade; a points-based assessment's grade rows use
-- the new `points` column instead and leave `value` NULL (the grade is converted live,
-- never stored) - so `value` can no longer be NOT NULL.
ALTER TABLE grade
    ALTER COLUMN value DROP NOT NULL,
    ADD COLUMN points NUMERIC(6,2);

ALTER TABLE grade
    ADD CONSTRAINT chk_grade_value_xor_points
        CHECK ((value IS NOT NULL AND points IS NULL) OR (value IS NULL AND points IS NOT NULL));

CREATE SEQUENCE points_grade_band_seq START WITH 1 INCREMENT BY 50;
SELECT setval('points_grade_band_seq', COALESCE((SELECT MAX(id) FROM points_grade_band), 0) + 1, false);
