-- A directory of every teacher who has made at least one authenticated request against this
-- instance (subject + best-effort email/display name), kept fresh by
-- security/TeacherDirectoryRecorder (an AuthenticationSuccessEvent listener). This is what lets a
-- class owner pick a colleague from a plain <select> when adding a co-owner (ClassUiResource's
-- addClassTeacher) instead of needing an invite-link/token flow - a teacher only becomes
-- selectable once they've logged in at least once.
--
-- teacher_subject stays a bare string on class_teacher/subject_teacher (no FK to this table) -
-- consistent with how it's modeled today; "who has access" and "who's known to exist" stay
-- decoupled concerns.
CREATE TABLE teacher (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject       VARCHAR(255) NOT NULL UNIQUE,
    email         VARCHAR(255),
    display_name  VARCHAR(255),
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at  TIMESTAMPTZ NOT NULL
);

CREATE SEQUENCE teacher_seq START WITH 1 INCREMENT BY 50;

-- Backfill from every subject already known via existing class_teacher/subject_teacher rows
-- (including "lehrer"/"dev-user" from V3's demo seed), so existing installs aren't left with an
-- empty directory before everyone's next login. No historical email/display name to recover.
INSERT INTO teacher (id, subject, first_seen_at, last_seen_at)
SELECT nextval('teacher_seq'), s.subject, now(), now()
FROM (
    SELECT teacher_subject AS subject FROM class_teacher
    UNION
    SELECT teacher_subject AS subject FROM subject_teacher
) s;

SELECT setval('teacher_seq', COALESCE((SELECT MAX(id) FROM teacher), 0) + 1, false);
