-- Verhaltensnoten: one behavior/conduct grade per (student, subject), entered directly by the
-- teacher - independent of Assessment/Grade/GradeService, never contributes to a subject's
-- academic average. No H1/H2 split: a single always-current value the teacher updates before
-- each report is printed, consistent with this app's anti-freeze design principle.

CREATE TABLE behavior_grade (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES student(id) ON DELETE CASCADE,
    subject_id BIGINT NOT NULL REFERENCES subject(id) ON DELETE CASCADE,
    value      NUMERIC(4,2) NOT NULL,
    UNIQUE (student_id, subject_id)
);

CREATE INDEX idx_behavior_grade_student ON behavior_grade(student_id);
CREATE INDEX idx_behavior_grade_subject ON behavior_grade(subject_id);

CREATE SEQUENCE behavior_grade_seq START WITH 1 INCREMENT BY 50;
SELECT setval('behavior_grade_seq', COALESCE((SELECT MAX(id) FROM behavior_grade), 0) + 1, false);
